### ISSUE TITLE
Issue in export Hebrew text - add UTF-8 BOM to CSV export

### ISSUE THREAD

**Issue by Royb10** [coston/json-to-csv-export#38]
Thanks for the great tool!
I found an issue - The CSV file should be saved as UTF-8 otherwise Excel and other encoding-sensitive applications may show gibberish instead of Hebrew characters.

You can see the Title column:
![utf-8 export issue](https://user-images.githubusercontent.com/49725353/197954134-0e1fa290-5a21-41b7-babd-c3e2dd210e2d.PNG)

If I open the file with Notepad or import it to excel using Excel Data tools - all good. 
I think the solution is to add UTF-8 BOM to CSV export, maybe this could help:
https://stackoverflow.com/questions/17879198/adding-utf-8-bom-to-string-blob/27975629#27975629

**Comment by coston** [comment]
Hey @Royb10, thank you for sharing this issue. The default encoding for blob is UTF-8, so we'd only need to add the BOM marker. Seems fine to me. Is there downside to doing this? (i'm wondering why it's not the default)

**Comment by Royb10** [comment]
Hi @coston, thanks for the quick reply!
From what I've checked and researched, I don't see any downside. really interesting why it's not the default...

**Comment by coston** [comment]
Hey @Royb10, BOM support is available in [v2.1.0](https://github.com/coston/json-to-csv-export/tree/v2.1.0)

**Comment by Royb10** [comment]
Works perfectly, thanks much!
