### ISSUE TITLE
Adding sep= to the top of file to help with opening csv files

### ISSUE THREAD

**Issue by mathijsfr** [coston/json-to-csv-export#50]
When adding a delimitter as follows:

```
const dataToConvert = {
    data: result,
    filename: `${props.name}.csv`,
    delimiter: ';',
    headers: Object.keys(result[0])
  }
```

The delimitter should be added at the top of the file to help with opening it.

![image](https://user-images.githubusercontent.com/22468642/225003344-bcc56c27-72d8-4250-ae53-2d560329729c.png)

**Comment by mathijsfr** [comment]
#51

**Comment by coston** [comment]
Hey @mathijsfr, thank you for the pull request and opening this issue. The solution here causes some compatibility issues with basic csv views (non-excel.) See the image below of when one opens the csv with Apple Numbers. 

<img width="1573" alt="image" src="https://github.com/coston/json-to-csv-export/assets/7424180/df835f63-354a-43ea-bd53-d588270f7dc6">
