### ISSUE TITLE
Use comma as default separator to comply with RFC-4180

### ISSUE THREAD

**Issue by zachelrath** [coston/json-to-csv-export#61]
Although Excel and some other programs are able to read semicolon-delimited files, the widely-adopted industry standard for CSV  files is [RFC-4180](https://www.ietf.org/rfc/rfc4180.txt), which specifies the use of commas as the delimiter. Which makes sense, considering that the name of the format is Comma Separated Values.

If this library just switched to using commas as the default delimiter, it would solve a lot of the compatibility issues that people have experienced, such as #50 . 

I was quite surprised to realize that the default for this library was semicolons.

**Comment by coston** [comment]
You're right, @zachelrath. I'm happy push a major version bump with this update if anyone wants to open a PR.

**Comment by zachelrath** [comment]
@coston PR submitted: https://github.com/coston/json-to-csv-export/pull/64

**Comment by coston** [comment]
json-to-csv-export@3.0.0 is published. 

Thank you, @zachelrath ⭐
